# Generated by Django 4.0.3 on 2022-03-09 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brokerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=4, help_text='в центах', max_digits=14)),
                ('buy_or_sale', models.CharField(choices=[('buy', 'Buy'), ('sale', 'Sale')], max_length=5)),
                ('has_tax', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=10)),
                ('amount', models.DecimalField(decimal_places=4, editable=False, max_digits=14, null=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brokerapp.broker')),
            ],
        ),
    ]
